version: "3.8"
services:
  web:
    restart: always
    build: ./auth-react-prj
    ports:
      - 80:3000
  api:
    restart: always
    build: ./AuthWebApi
    environment:
      - "ASPNETCORE_URLS=http://+:80"
      - "ASPNETCORE_ENVIRONMENT=Development"
    ports:
      - 5000:80
